// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_proto.proto

package com.FoolRpc.rpc.protocol;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *服务描述符
   * </pre>
   *
   * <code>.protocol.ServiceDescriptor serviceDescriptor = 1;</code>
   * @return Whether the serviceDescriptor field is set.
   */
  boolean hasServiceDescriptor();
  /**
   * <pre>
   *服务描述符
   * </pre>
   *
   * <code>.protocol.ServiceDescriptor serviceDescriptor = 1;</code>
   * @return The serviceDescriptor.
   */
  com.FoolRpc.rpc.protocol.ServiceDescriptor getServiceDescriptor();
  /**
   * <pre>
   *服务描述符
   * </pre>
   *
   * <code>.protocol.ServiceDescriptor serviceDescriptor = 1;</code>
   */
  com.FoolRpc.rpc.protocol.ServiceDescriptorOrBuilder getServiceDescriptorOrBuilder();

  /**
   * <pre>
   *具体参数列表
   * </pre>
   *
   * <code>repeated bytes parameter = 2;</code>
   * @return A list containing the parameter.
   */
  java.util.List<com.google.protobuf.ByteString> getParameterList();
  /**
   * <pre>
   *具体参数列表
   * </pre>
   *
   * <code>repeated bytes parameter = 2;</code>
   * @return The count of parameter.
   */
  int getParameterCount();
  /**
   * <pre>
   *具体参数列表
   * </pre>
   *
   * <code>repeated bytes parameter = 2;</code>
   * @param index The index of the element to return.
   * @return The parameter at the given index.
   */
  com.google.protobuf.ByteString getParameter(int index);
}
