// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_proto.proto

package com.FoolRpc.rpc.protocol;

/**
 * Protobuf type {@code protocol.ServiceDescriptor}
 */
public final class ServiceDescriptor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.ServiceDescriptor)
    ServiceDescriptorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceDescriptor.newBuilder() to construct.
  private ServiceDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceDescriptor() {
    clazz_ = "";
    methodName_ = "";
    returnType_ = "";
    parameterType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServiceDescriptor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceDescriptor(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clazz_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            methodName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            returnType_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              parameterType_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            parameterType_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        parameterType_ = parameterType_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.FoolRpc.rpc.protocol.RpcProto.internal_static_protocol_ServiceDescriptor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.FoolRpc.rpc.protocol.RpcProto.internal_static_protocol_ServiceDescriptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.FoolRpc.rpc.protocol.ServiceDescriptor.class, com.FoolRpc.rpc.protocol.ServiceDescriptor.Builder.class);
  }

  public static final int CLAZZ_FIELD_NUMBER = 1;
  private volatile java.lang.Object clazz_;
  /**
   * <pre>
   *访问哪个类
   * </pre>
   *
   * <code>string clazz = 1;</code>
   * @return The clazz.
   */
  @java.lang.Override
  public java.lang.String getClazz() {
    java.lang.Object ref = clazz_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clazz_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *访问哪个类
   * </pre>
   *
   * <code>string clazz = 1;</code>
   * @return The bytes for clazz.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClazzBytes() {
    java.lang.Object ref = clazz_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clazz_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHODNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object methodName_;
  /**
   * <pre>
   *方法名称
   * </pre>
   *
   * <code>string methodName = 2;</code>
   * @return The methodName.
   */
  @java.lang.Override
  public java.lang.String getMethodName() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      methodName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *方法名称
   * </pre>
   *
   * <code>string methodName = 2;</code>
   * @return The bytes for methodName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodNameBytes() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      methodName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETURNTYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object returnType_;
  /**
   * <pre>
   *返回值类型
   * </pre>
   *
   * <code>string returnType = 3;</code>
   * @return The returnType.
   */
  @java.lang.Override
  public java.lang.String getReturnType() {
    java.lang.Object ref = returnType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *返回值类型
   * </pre>
   *
   * <code>string returnType = 3;</code>
   * @return The bytes for returnType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReturnTypeBytes() {
    java.lang.Object ref = returnType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMETERTYPE_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList parameterType_;
  /**
   * <pre>
   *参数类型 可多个
   * </pre>
   *
   * <code>repeated string parameterType = 4;</code>
   * @return A list containing the parameterType.
   */
  public com.google.protobuf.ProtocolStringList
      getParameterTypeList() {
    return parameterType_;
  }
  /**
   * <pre>
   *参数类型 可多个
   * </pre>
   *
   * <code>repeated string parameterType = 4;</code>
   * @return The count of parameterType.
   */
  public int getParameterTypeCount() {
    return parameterType_.size();
  }
  /**
   * <pre>
   *参数类型 可多个
   * </pre>
   *
   * <code>repeated string parameterType = 4;</code>
   * @param index The index of the element to return.
   * @return The parameterType at the given index.
   */
  public java.lang.String getParameterType(int index) {
    return parameterType_.get(index);
  }
  /**
   * <pre>
   *参数类型 可多个
   * </pre>
   *
   * <code>repeated string parameterType = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parameterType at the given index.
   */
  public com.google.protobuf.ByteString
      getParameterTypeBytes(int index) {
    return parameterType_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clazz_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clazz_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(returnType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, returnType_);
    }
    for (int i = 0; i < parameterType_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parameterType_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clazz_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clazz_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(returnType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, returnType_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < parameterType_.size(); i++) {
        dataSize += computeStringSizeNoTag(parameterType_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParameterTypeList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.FoolRpc.rpc.protocol.ServiceDescriptor)) {
      return super.equals(obj);
    }
    com.FoolRpc.rpc.protocol.ServiceDescriptor other = (com.FoolRpc.rpc.protocol.ServiceDescriptor) obj;

    if (!getClazz()
        .equals(other.getClazz())) return false;
    if (!getMethodName()
        .equals(other.getMethodName())) return false;
    if (!getReturnType()
        .equals(other.getReturnType())) return false;
    if (!getParameterTypeList()
        .equals(other.getParameterTypeList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLAZZ_FIELD_NUMBER;
    hash = (53 * hash) + getClazz().hashCode();
    hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
    hash = (53 * hash) + getMethodName().hashCode();
    hash = (37 * hash) + RETURNTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getReturnType().hashCode();
    if (getParameterTypeCount() > 0) {
      hash = (37 * hash) + PARAMETERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getParameterTypeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.FoolRpc.rpc.protocol.ServiceDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.FoolRpc.rpc.protocol.ServiceDescriptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.ServiceDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.ServiceDescriptor)
      com.FoolRpc.rpc.protocol.ServiceDescriptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.FoolRpc.rpc.protocol.RpcProto.internal_static_protocol_ServiceDescriptor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.FoolRpc.rpc.protocol.RpcProto.internal_static_protocol_ServiceDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.FoolRpc.rpc.protocol.ServiceDescriptor.class, com.FoolRpc.rpc.protocol.ServiceDescriptor.Builder.class);
    }

    // Construct using com.FoolRpc.rpc.protocol.ServiceDescriptor.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clazz_ = "";

      methodName_ = "";

      returnType_ = "";

      parameterType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.FoolRpc.rpc.protocol.RpcProto.internal_static_protocol_ServiceDescriptor_descriptor;
    }

    @java.lang.Override
    public com.FoolRpc.rpc.protocol.ServiceDescriptor getDefaultInstanceForType() {
      return com.FoolRpc.rpc.protocol.ServiceDescriptor.getDefaultInstance();
    }

    @java.lang.Override
    public com.FoolRpc.rpc.protocol.ServiceDescriptor build() {
      com.FoolRpc.rpc.protocol.ServiceDescriptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.FoolRpc.rpc.protocol.ServiceDescriptor buildPartial() {
      com.FoolRpc.rpc.protocol.ServiceDescriptor result = new com.FoolRpc.rpc.protocol.ServiceDescriptor(this);
      int from_bitField0_ = bitField0_;
      result.clazz_ = clazz_;
      result.methodName_ = methodName_;
      result.returnType_ = returnType_;
      if (((bitField0_ & 0x00000001) != 0)) {
        parameterType_ = parameterType_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.parameterType_ = parameterType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.FoolRpc.rpc.protocol.ServiceDescriptor) {
        return mergeFrom((com.FoolRpc.rpc.protocol.ServiceDescriptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.FoolRpc.rpc.protocol.ServiceDescriptor other) {
      if (other == com.FoolRpc.rpc.protocol.ServiceDescriptor.getDefaultInstance()) return this;
      if (!other.getClazz().isEmpty()) {
        clazz_ = other.clazz_;
        onChanged();
      }
      if (!other.getMethodName().isEmpty()) {
        methodName_ = other.methodName_;
        onChanged();
      }
      if (!other.getReturnType().isEmpty()) {
        returnType_ = other.returnType_;
        onChanged();
      }
      if (!other.parameterType_.isEmpty()) {
        if (parameterType_.isEmpty()) {
          parameterType_ = other.parameterType_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureParameterTypeIsMutable();
          parameterType_.addAll(other.parameterType_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.FoolRpc.rpc.protocol.ServiceDescriptor parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.FoolRpc.rpc.protocol.ServiceDescriptor) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object clazz_ = "";
    /**
     * <pre>
     *访问哪个类
     * </pre>
     *
     * <code>string clazz = 1;</code>
     * @return The clazz.
     */
    public java.lang.String getClazz() {
      java.lang.Object ref = clazz_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clazz_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *访问哪个类
     * </pre>
     *
     * <code>string clazz = 1;</code>
     * @return The bytes for clazz.
     */
    public com.google.protobuf.ByteString
        getClazzBytes() {
      java.lang.Object ref = clazz_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clazz_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *访问哪个类
     * </pre>
     *
     * <code>string clazz = 1;</code>
     * @param value The clazz to set.
     * @return This builder for chaining.
     */
    public Builder setClazz(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clazz_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *访问哪个类
     * </pre>
     *
     * <code>string clazz = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClazz() {
      
      clazz_ = getDefaultInstance().getClazz();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *访问哪个类
     * </pre>
     *
     * <code>string clazz = 1;</code>
     * @param value The bytes for clazz to set.
     * @return This builder for chaining.
     */
    public Builder setClazzBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clazz_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object methodName_ = "";
    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @param value The methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      methodName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodName() {
      
      methodName_ = getDefaultInstance().getMethodName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *方法名称
     * </pre>
     *
     * <code>string methodName = 2;</code>
     * @param value The bytes for methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      methodName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object returnType_ = "";
    /**
     * <pre>
     *返回值类型
     * </pre>
     *
     * <code>string returnType = 3;</code>
     * @return The returnType.
     */
    public java.lang.String getReturnType() {
      java.lang.Object ref = returnType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *返回值类型
     * </pre>
     *
     * <code>string returnType = 3;</code>
     * @return The bytes for returnType.
     */
    public com.google.protobuf.ByteString
        getReturnTypeBytes() {
      java.lang.Object ref = returnType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *返回值类型
     * </pre>
     *
     * <code>string returnType = 3;</code>
     * @param value The returnType to set.
     * @return This builder for chaining.
     */
    public Builder setReturnType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *返回值类型
     * </pre>
     *
     * <code>string returnType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReturnType() {
      
      returnType_ = getDefaultInstance().getReturnType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *返回值类型
     * </pre>
     *
     * <code>string returnType = 3;</code>
     * @param value The bytes for returnType to set.
     * @return This builder for chaining.
     */
    public Builder setReturnTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnType_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList parameterType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureParameterTypeIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        parameterType_ = new com.google.protobuf.LazyStringArrayList(parameterType_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @return A list containing the parameterType.
     */
    public com.google.protobuf.ProtocolStringList
        getParameterTypeList() {
      return parameterType_.getUnmodifiableView();
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @return The count of parameterType.
     */
    public int getParameterTypeCount() {
      return parameterType_.size();
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @param index The index of the element to return.
     * @return The parameterType at the given index.
     */
    public java.lang.String getParameterType(int index) {
      return parameterType_.get(index);
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterType at the given index.
     */
    public com.google.protobuf.ByteString
        getParameterTypeBytes(int index) {
      return parameterType_.getByteString(index);
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @param index The index to set the value at.
     * @param value The parameterType to set.
     * @return This builder for chaining.
     */
    public Builder setParameterType(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterTypeIsMutable();
      parameterType_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @param value The parameterType to add.
     * @return This builder for chaining.
     */
    public Builder addParameterType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterTypeIsMutable();
      parameterType_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @param values The parameterType to add.
     * @return This builder for chaining.
     */
    public Builder addAllParameterType(
        java.lang.Iterable<java.lang.String> values) {
      ensureParameterTypeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, parameterType_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearParameterType() {
      parameterType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *参数类型 可多个
     * </pre>
     *
     * <code>repeated string parameterType = 4;</code>
     * @param value The bytes of the parameterType to add.
     * @return This builder for chaining.
     */
    public Builder addParameterTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureParameterTypeIsMutable();
      parameterType_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.ServiceDescriptor)
  }

  // @@protoc_insertion_point(class_scope:protocol.ServiceDescriptor)
  private static final com.FoolRpc.rpc.protocol.ServiceDescriptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.FoolRpc.rpc.protocol.ServiceDescriptor();
  }

  public static com.FoolRpc.rpc.protocol.ServiceDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceDescriptor>
      PARSER = new com.google.protobuf.AbstractParser<ServiceDescriptor>() {
    @java.lang.Override
    public ServiceDescriptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceDescriptor(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceDescriptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceDescriptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.FoolRpc.rpc.protocol.ServiceDescriptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

