// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_proto.proto

package cn.llynsyw.rpc.protocol;

public interface ServiceDescriptorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ServiceDescriptor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *访问哪个类
   * </pre>
   *
   * <code>string clazz = 1;</code>
   * @return The clazz.
   */
  java.lang.String getClazz();
  /**
   * <pre>
   *访问哪个类
   * </pre>
   *
   * <code>string clazz = 1;</code>
   * @return The bytes for clazz.
   */
  com.google.protobuf.ByteString
      getClazzBytes();

  /**
   * <pre>
   *方法名称
   * </pre>
   *
   * <code>string methodName = 2;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <pre>
   *方法名称
   * </pre>
   *
   * <code>string methodName = 2;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <pre>
   *返回值类型
   * </pre>
   *
   * <code>string returnType = 3;</code>
   * @return The returnType.
   */
  java.lang.String getReturnType();
  /**
   * <pre>
   *返回值类型
   * </pre>
   *
   * <code>string returnType = 3;</code>
   * @return The bytes for returnType.
   */
  com.google.protobuf.ByteString
      getReturnTypeBytes();

  /**
   * <pre>
   *参数类型 可多个
   * </pre>
   *
   * <code>repeated string parameterType = 4;</code>
   * @return A list containing the parameterType.
   */
  java.util.List<java.lang.String>
      getParameterTypeList();
  /**
   * <pre>
   *参数类型 可多个
   * </pre>
   *
   * <code>repeated string parameterType = 4;</code>
   * @return The count of parameterType.
   */
  int getParameterTypeCount();
  /**
   * <pre>
   *参数类型 可多个
   * </pre>
   *
   * <code>repeated string parameterType = 4;</code>
   * @param index The index of the element to return.
   * @return The parameterType at the given index.
   */
  java.lang.String getParameterType(int index);
  /**
   * <pre>
   *参数类型 可多个
   * </pre>
   *
   * <code>repeated string parameterType = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parameterType at the given index.
   */
  com.google.protobuf.ByteString
      getParameterTypeBytes(int index);
}
